import { AiFillStar } from "react-icons/ai";
import acer_laptops from "../assets/images/acer_laptops.jpg";
import black_t_shirt from "../assets/images/black_t_shirt.jpg";
import black_salwar from "../assets/images/black_salwar.jpg";
import black_suit from "../assets/images/black_suit.jpg";
import blue_frock from "../assets/images/blue_frock.jpg";
import blue_kids_t_shirt from "../assets/images/blue_kids_t_shirt.jpg";
import blue_lehenga from "../assets/images/blue_lehenga.jpg";
import blue_salwar from "../assets/images/blue_salwar.jpg";
import blue_shirt_kids from "../assets/images/blue_shirt_kids.jpg";

import blue_suit from "../assets/images/blue_suit.jpg";
import blue_tshirt from "../assets/images/blue_tshirt.jpg";
import brown_shirt from "../assets/images/brown_shirt.jpg";
import conf_table1 from "../assets/images/conf_table1.jpg";
import conf_table2 from "../assets/images/conf_table2.jpg";
import conf_table3 from "../assets/images/conf_table3.jpg";
import dell_laptop from "../assets/images/dell_laptop.jpg";
import desk1 from "../assets/images/desk1.jpg";
import desk2 from "../assets/images/desk2.jpg";
import desk3 from "../assets/images/desk3.jpg";
import desk4 from "../assets/images/desk4.jpg";
import footwear1 from "../assets/images/footwear1.jpg";
import footwear6 from "../assets/images/footwear6.jpg";
import footwear2 from "../assets/images/footwear2.jpg";
import footwear3 from "../assets/images/footwear3.jpg";
import footwear4 from "../assets/images/footwear4.jpg";
import footwear5 from "../assets/images/footwear5.jpg";
import galaxy_phone from "../assets/images/galaxy_phone.jpg";
import gold_lehenga from "../assets/images/gold_lehenga.jpg";
import green_saree from "../assets/images/green_saree.jpg";
import green_suit from "../assets/images/green_suit.jpg";
import green_tshirt from "../assets/images/green_tshirt.jpg";
import grey_shirt from "../assets/images/grey_shirt.jpg";
import handbag1 from "../assets/images/handbag1.jpg";
import handbag2 from "../assets/images/handbag2.jpg";
import i_phone14 from "../assets/images/i_phone14.jpg";
import laptop_bag1 from "../assets/images/laptop_bag1.jpg";
import macbook_laptop from "../assets/images/macbook_laptop.jpg";
import one_plus from "../assets/images/one_plus.jpg";
import orange_frock from "../assets/images/orange_frock.jpg";
import orange_kids_t_shirt from "../assets/images/orange_kids_t_shirt.jpg";
import orange_shirt_kids from "../assets/images/orange_shirt_kids.jpg";
import orange_shirt from "../assets/images/orange_shirt.jpg";
import pink_kids_t_shirt from "../assets/images/pink_kids_t_shirt.jpg";
import pink_lehenga from "../assets/images/pink_lehenga.jpg";
import pink_salwar from "../assets/images/pink_salwar.jpg";
import pink_shirt from "../assets/images/pink_shirt.jpg";
import pink_tshirt from "../assets/images/pink_tshirt.jpg";
import red_kids_shirt from "../assets/images/red_kids_shirt.jpg";
import red_saree from "../assets/images/red_saree.jpg";
import samsung_ac from "../assets/images/samsung_ac.jpg";
import schoolbag1 from "../assets/images/schoolbag1.jpg";
import silver_chain1 from "../assets/images/silver_chain1.jpg";
import silver_chain2 from "../assets/images/silver_chain2.jpg";
import silver_chain3 from "../assets/images/silver_chain3.jpg";
import silver_chain4 from "../assets/images/silver_chain4.jpg";
import violet_frock from "../assets/images/violet_frock.jpg";
import wardrobe1 from "../assets/images/wardrobe1.jpg";
import wardrobe2 from "../assets/images/wardrobe2.jpg";
import wardrobe3 from "../assets/images/wardrobe3.jpg";
import yellow_saree from "../assets/images/yellow_saree.jpg";
import yellow_tshirt from "../assets/images/yellow_tshirt.jpg";

const data = [
  {
    img: acer_laptops,
    title: "Acer Laptop",
    star: <AiFillStar className="product-rating" />,
    reviews: "(25.7k+ reviews)",
    prevPrice: "Rs.80000",
    newPrice: "50000",
    group: "Electronics",
    color: "blue",
    category: "Laptop",
  },
  {
    img: black_t_shirt,
    title: "Van Heusen T-Shirt ",
    star: <AiFillStar className="product-rating" />,
    reviews: "(3.5k+ reviews)",
    prevPrice: "Rs.10000",
    newPrice: "5000",
    group: "Men",
    color: "black",
    category: "t-shirts",
  },

  {
    img: black_salwar,
    title: "Avasa Black Salwar",
    star: <AiFillStar className="product-rating" />,
    reviews: "(5.3k+ reviews)",
    prevPrice: "Rs.1700",
    newPrice: "1000",
    group: "Women",
    color: "black",
    category: "salwar",
  },
  {
    img: black_suit,
    title: "Park Avenue Suit",
    star: <AiFillStar className="product-rating" />,
    reviews: "(10k+ reviews)",
    prevPrice: "Rs.25000",
    newPrice: "20000",
    group: "Men",
    color: "black",
    category: "suits",
  },
  {
    img: blue_frock,
    title: "Trendy Blue Frock",
    star: <AiFillStar className="product-rating" />,
    reviews: "(11.2k+ reviews)",
    prevPrice: "Rs.2400",
    newPrice: "1000",
    group: "Kids",
    color: "blue",
    category: "frock",
  },
  {
    img: blue_kids_t_shirt,
    title: "Kids Blue T-shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(3.5k+ reviews)",
    prevPrice: "Rs.2000",
    newPrice: "500",
    group: "Kids",
    color: "blue",
    category: "kids t-shirt",
  },

  {
    img: blue_lehenga,
    title: "Blue Lehenga",
    star: <AiFillStar className="product-rating" />,
    reviews: "(30.4k+ reviews)",
    prevPrice: "Rs.11400",
    newPrice: "5000",
    group: "Women",
    color: "blue",
    category: "lehenga",
  },

  {
    img: blue_salwar,
    title: "Elegant Blue Salwar",
    star: <AiFillStar className="product-rating" />,
    reviews: "(13.8k+ reviews)",
    prevPrice: "Rs.5000",
    newPrice: "1000",
    group: "Women",
    color: "blue",
    category: "salwar",
  },

  {
    img: blue_shirt_kids,
    title: "Kids T-shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(7.4k+ reviews)",
    prevPrice: "Rs.800",
    newPrice: "500",
    group: "Kids",
    color: "blue",
    category: "kids t-shirt",
  },

  {
    img: samsung_ac,
    title: "Blue Star Air Conditioner",
    star: <AiFillStar className="product-rating" />,
    reviews: "( 42.9k+ reviews)",
    prevPrice: "Rs.70000",
    newPrice: "50000",
    group: "Electronics",
    color: "White",
    category: "Air Conditioner",
  },
  {
    img: blue_suit,
    title: "Peter England Suit",
    star: <AiFillStar className="product-rating" />,
    reviews: "(14.9k+ reviews)",
    prevPrice: "Rs.20000",
    newPrice: "10000",
    group: "Women",
    color: "blue",
    category: "suits",
  },
  {
    img: blue_tshirt,
    title: "Men's T-Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(5.5k+ reviews)",
    prevPrice: "Rs.1500",
    newPrice: "500",
    group: "Men",
    color: "blue",
    category: "t-shirts",
  },
  {
    img: brown_shirt,
    title: "Raymonds shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(7.6k+ reviews)",
    prevPrice: "Rs.3000",
    newPrice: "1000",
    group: "Men",
    color: "brown",
    category: "shirts",
  },
  {
    img: conf_table1,
    title: "Conference Table",
    star: <AiFillStar className="product-rating" />,
    reviews: "(10.2k+ reviews)",
    prevPrice: "Rs.50000",
    newPrice: "40000",
    group: "Furniture",
    color: "white",
    category: "conference table",
  },

  {
    img: conf_table2,
    title: "Office Conference Table",
    star: <AiFillStar className="product-rating" />,
    reviews: "(26.3k+ reviews)",
    prevPrice: "Rs.50000",
    newPrice: "40000",
    group: "Furniture",
    color: "black",
    category: "conference table",
  },
  {
    img: conf_table3,
    title: "Office Table",
    star: <AiFillStar className="product-rating" />,
    reviews: "(60.6k+ reviews)",
    prevPrice: "Rs.68000",
    newPrice: "50000",
    group: "Furniture",
    color: "white",
    category: "conference table",
  },

  {
    img: dell_laptop,
    title: "Dell Laptop",
    star: <AiFillStar className="product-rating" />,
    reviews: "(49k+ reviews)",
    prevPrice: "Rs.70000",
    newPrice: "50000",
    group: "Electronics",
    color: "Grey",
    category: "laptop",
  },
  {
    img: desk1,
    title: "Classic Wooden Desk",
    star: <AiFillStar className="product-rating" />,
    reviews: "(23.7k+ reviews)",
    prevPrice: "Rs.40000",
    newPrice: "20000",
    group: "Furniture",
    color: "white",
    category: "desk",
  },
  {
    img: desk2,
    title: "Study Desk",
    star: <AiFillStar className="product-rating" />,
    reviews: "(23.4k+ reviews)",
    prevPrice: "Rs.24000",
    newPrice: "20000",
    group: "Furniture",
    color: "black",
    category: "desk",
  },
  {
    img: desk3,
    title: "Modern Office Desk",
    star: <AiFillStar className="product-rating" />,
    reviews: "(43.1k+ reviews)",
    prevPrice: "Rs.80000",
    newPrice: "50000",
    group: "Furniture",
    color: "brown",
    category: "desk",
  },
  {
    img: desk4,
    title: "Classic Office Desk",
    star: <AiFillStar className="product-rating" />,
    reviews: "(33.5k+ reviews)",
    prevPrice: "Rs.25000",
    newPrice: "20000",
    group: "Furniture",
    color: "brown",
    category: "desk",
  },

  {
    img: footwear1,
    title: "Bata footwear",
    star: <AiFillStar className="product-rating" />,
    reviews: "(15.2k+ reviews)",
    prevPrice: "Rs.3200",
    newPrice: "1000",
    group: "Women",
    color: "blue",
    category: "footwear",
  },

  {
    img: footwear2,
    title: "Catwalk footwear",
    star: <AiFillStar className="product-rating" />,
    reviews: "(12k+ reviews)",
    prevPrice: "Rs.4000",
    newPrice: "1000",
    group: "Women",
    color: "White",
    category: "footwear",
  },
  {
    img: footwear3,
    title: "Chunky High Heel",
    star: <AiFillStar className="product-rating" />,
    reviews: "(13.1k+ reviews)",
    prevPrice: "Rs.10200",
    newPrice: "5000",
    group: "Women",
    color: "brown",
    category: "footwear",
  },
  {
    img: footwear4,
    title: "Bata Shoe",
    star: <AiFillStar className="product-rating" />,
    reviews: "(16.3k+ reviews)",
    prevPrice: "Rs.15000",
    newPrice: "5000",
    group: "Men",
    color: "white",
    category: "footwear",
  },
  {
    img: footwear5,
    title: "Nike Shoe",
    star: <AiFillStar className="product-rating" />,
    reviews: "(12.8k+ reviews)",
    prevPrice: "Rs.5800",
    newPrice: "1000",
    group: "Men",
    color: "grey",
    category: "footwear",
  },
  {
    img: footwear6,
    title: "Adidas Shoe",
    star: <AiFillStar className="product-rating" />,
    reviews: "( 20.3k+ reviews)",
    prevPrice: "Rs.8000",
    newPrice: "5000",
    group: "Men",
    color: "blue",
    category: "footwear",
  },

  {
    img: galaxy_phone,
    title: "Samsung Galaxy Phone",
    star: <AiFillStar className="product-rating" />,
    reviews: "(33.3k+ reviews)",
    prevPrice: "Rs.50000",
    newPrice: "40000",
    group: "Electronics",
    color: "blue",
    category: "mobile phone",
  },
  {
    img: gold_lehenga,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="product-rating" />,
    reviews: "(16.8k+ reviews)",
    prevPrice: "Rs.26000",
    newPrice: "20000",
    group: "Women",
    color: "gold",
    category: "lehenga",
  },
  {
    img: green_saree,
    title: "Fancy Saree",
    star: <AiFillStar className="product-rating" />,
    reviews: "(6.9k+ reviews)",
    prevPrice: "Rs.9000",
    newPrice: "5000",
    group: "Women",
    color: "green",
    category: "saree",
  },

  {
    img: green_suit,
    title: "Raymonds Suit",
    star: <AiFillStar className="product-rating" />,
    reviews: "(25.3k+ reviews)",
    prevPrice: "Rs.26000",
    newPrice: "20000",
    group: "Men",
    color: "green",
    category: "suits",
  },
  {
    img: green_tshirt,
    title: "Peter England Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(12k+ reviews)",
    prevPrice: "Rs.3400",
    newPrice: "1000",
    group: "Men",
    color: "green",
    category: "shirts",
  },
  {
    img: grey_shirt,
    title: "Adidas Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(3.7k+ reviews)",
    prevPrice: "Rs.8500",
    newPrice: "5000",
    group: "Men",
    color: "grey",
    category: "shirts",
  },
  {
    img: handbag1,
    title: "Western Handbag",
    star: <AiFillStar className="product-rating" />,
    reviews: "(6.3k+ reviews)",
    prevPrice: "Rs.8000",
    newPrice: "5000",
    group: "Other Accessories",
    color: "white",
    category: "bags",
  },

  {
    img: handbag2,
    title: "Women Handbags",
    star: <AiFillStar className="product-rating" />,
    reviews: "(6.9k+ reviews)",
    prevPrice: "Rs.7000",
    newPrice: "5000",
    group: "Other Accessories",
    color: "pink",
    category: "bags",
  },

  {
    img: i_phone14,
    title: "Apple I-Phone",
    star: <AiFillStar className="product-rating" />,
    reviews: "(89.9k+ reviews)",
    prevPrice: "Rs.1,20,000",
    newPrice: "100000",
    group: "Electronics",
    color: "black",
    category: "mobile phone",
  },

  {
    img: laptop_bag1,
    title: "Laptop Bag",
    star: <AiFillStar className="product-rating" />,
    reviews: "(8.2k+ reviews)",
    prevPrice: "Rs.2000",
    newPrice: "1000",
    group: "Other Accessories",
    color: "black",
    category: "bags",
  },

  {
    img: macbook_laptop,
    title: "Apple Macbook Laptop",
    star: <AiFillStar className="product-rating" />,
    reviews: "(99.3k+ reviews)",
    prevPrice: "Rs.180000",
    newPrice: "150000",
    group: "Electronics",
    color: "grey",
    category: "laptop",
  },
  {
    img: one_plus,
    title: "One Plus Mobile",
    star: <AiFillStar className="product-rating" />,
    reviews: "(34.6k+ reviews)",
    prevPrice: "Rs.100000",
    newPrice: "80000",
    group: "Electronics",
    color: "black",
    category: "mobile phone",
  },
  {
    img: orange_frock,
    title: "Avasa frock",
    star: <AiFillStar className="product-rating" />,
    reviews: "(13.2k+ reviews)",
    prevPrice: "Rs.1800",
    newPrice: "1000",
    group: "Kids",
    color: "orange",
    category: "frock",
  },
  {
    img: orange_kids_t_shirt,
    title: "Casual Orange Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(3.2k+ reviews)",
    prevPrice: "Rs.1000",
    newPrice: "500",
    group: "Kids",
    color: "orange",
    category: "kids t-shirt",
  },
  {
    img: orange_shirt_kids,
    title: "Kids Casual Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(10.7k+ reviews)",
    prevPrice: "Rs.1400",
    newPrice: "500",
    group: "Kids",
    color: "orange",
    category: "kids shirt",
  },

  {
    img: orange_shirt,
    title: "Louis Philippe Shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(11.3k+ reviews)",
    prevPrice: "Rs.5600",
    newPrice: "5000",
    group: "Men",
    color: "orange",
    category: "shirts",
  },
  {
    img: samsung_ac,
    title: "Orient Air Conditioner",
    star: <AiFillStar className="product-rating" />,
    reviews: "(32.6k+ reviews)",
    prevPrice: "Rs.130000",
    newPrice: "120000",
    group: "Electronics",
    color: "white",
    category: "air conditioner",
  },
  {
    img: pink_kids_t_shirt,
    title: "Kids Casual Pink T-shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(7.7k+ reviews)",
    prevPrice: "Rs.2000",
    newPrice: "500",
    group: "Kids",
    color: "pink",
    category: "kids t-shirt",
  },
  {
    img: pink_lehenga,
    title: "Bridal Lehenga",
    star: <AiFillStar className="product-rating" />,
    reviews: "(34.6k+ reviews)",
    prevPrice: "Rs.23000",
    newPrice: "20000",
    group: "Women",
    color: "pink",
    category: "sandals",
  },
  {
    img: pink_salwar,
    title: "Casual salwar",
    star: <AiFillStar className="product-rating" />,
    reviews: "(15.3k+ reviews)",
    prevPrice: "Rs.5800",
    newPrice: "2000",
    group: "Women",
    color: "pink",
    category: "salwar",
  },
  {
    img: pink_shirt,
    title: "Adidas Shirt for Men",
    star: <AiFillStar className="product-rating" />,
    reviews: "(20.2k+ reviews)",
    prevPrice: "Rs.7000",
    newPrice: "5000",
    group: "Men",
    color: "pink",
    category: "shirts",
  },
  {
    img: pink_tshirt,
    title: "Allen Solly shirt",
    star: <AiFillStar className="product-rating" />,
    reviews: "(19.6k+ reviews)",
    prevPrice: "Rs.11000",
    newPrice: "10000",
    group: "Men",
    color: "pink",
    category: "t-shirt",
  },
  {
    img: red_kids_shirt,
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="product-rating" />,
    reviews: "(11.1k+ reviews)",
    prevPrice: "Rs.1200",
    newPrice: "500",
    group: "Kids",
    color: "red",
    category: "kids shirt",
  },
  {
    img: red_saree,
    title: "Party wear for women",
    star: <AiFillStar className="product-rating" />,
    reviews: "(28.2k+ reviews)",
    prevPrice: "Rs.12300",
    newPrice: "10000",
    group: "Women",
    color: "red",
    category: "saree",
  },

  {
    img: samsung_ac,
    title: "Samsung Ac",
    star: <AiFillStar className="product-rating" />,
    reviews: "(45.3k+ reviews)",
    prevPrice: "Rs.48000",
    newPrice: "40000",
    group: "Electronics",
    color: "white",
    category: "air conditioner",
  },
  {
    img: schoolbag1,
    title: "Casual Bag",
    star: <AiFillStar className="product-rating" />,
    reviews: "(1.5k+ reviews)",
    prevPrice: "Rs.8500",
    newPrice: "5000",
    group: "Other Accessories",
    color: "blue",
    category: "bags",
  },
  {
    img: silver_chain1,
    title: "Amore Fashion Set",
    star: <AiFillStar className="product-rating" />,
    reviews: "(26.4k+ reviews)",
    prevPrice: "Rs.29000",
    newPrice: "10000",
    group: "Other Accessories",
    color: "grey",
    category: "silver chain",
  },
  {
    img: silver_chain2,
    title: "Bridal Fashion set",
    star: <AiFillStar className="product-rating" />,
    reviews: "(14.7k+ reviews)",
    prevPrice: "Rs.15000",
    newPrice: "10000",
    group: "Other Accessories",
    color: "grey",
    category: "silver chain",
  },
  {
    img: silver_chain3,
    title: "Wedding Fashion Chain",
    star: <AiFillStar className="product-rating" />,
    reviews: "(31k+ reviews)",
    prevPrice: "Rs.12000",
    newPrice: "10000",
    group: "Other Accessories",
    color: "grey",
    category: "silver chain",
  },
  {
    img: silver_chain4,
    title: "Casual Fashion Set",
    star: <AiFillStar className="product-rating" />,
    reviews: "(20.4k+ reviews)",
    prevPrice: "Rs.21300",
    newPrice: "20000",
    group: "Other Accessories",
    color: "grey",
    category: "silver chain",
  },
  {
    img: violet_frock,
    title: "Party wear for kids",
    star: <AiFillStar className="product-rating" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.6500",
    newPrice: "5000",
    group: "Kids",
    color: "violet",
    category: "flats",
  },
  {
    img: wardrobe1,
    title: "Wadrobe Classic",
    star: <AiFillStar className="product-rating" />,
    reviews: "(12.6k+ reviews)",
    prevPrice: "Rs.25000",
    newPrice: "20000",
    group: "Furniture",
    color: "brown",
    category: "wardrobe",
  },
  {
    img: wardrobe2,
    title: "Wadrobe",
    star: <AiFillStar className="product-rating" />,
    reviews: "(28.3k+ reviews)",
    prevPrice: "Rs.59900",
    newPrice: "50000",
    group: "Furniture",
    color: "black",
    category: "wardrobe",
  },
  {
    img: wardrobe3,
    title: "Giant Wardrobe",
    star: <AiFillStar className="product-rating" />,
    reviews: "(24.3k+ reviews)",
    prevPrice: "Rs.50300",
    newPrice: "40000",
    group: "Furniture",
    color: "grey",
    category: "wardrobe",
  },
  {
    img: yellow_saree,
    title: "Wedding saree",
    star: <AiFillStar className="product-rating" />,
    reviews: "(5.3k+ reviews)",
    prevPrice: "Rs.10000",
    newPrice: "5000",
    group: "Women",
    color: "yellow",
    category: "saree",
  },
  {
    img: yellow_tshirt,
    title: "Casyal Mens Wear",
    star: <AiFillStar className="product-rating" />,
    reviews: "(5.5k+ reviews)",
    prevPrice: "Rs.2300",
    newPrice: "1000",
    group: "Men",
    color: "yellow",
    category: "t-shirts",
  },
];

export default data;
